language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_script:
after_script:
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.2.2
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
gemfile: .gemfile
